version: "3.5"
services:
    flask:
        build: ./flask
        container_name: flask
        restart: always
        env_file: 
            - ./.env
        volumes:
            - ./flask:/app
        
        # for deployment
        expose: 
            - 8080
        # for development 
        ports:
            - "5000:5000"
        links: 
            - mysql:db

    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        env_file:
            - ./.env
        ports: 
            - "32000:3306"
        volumes:
            - ./mysql/scripts:/docker-entrypoint-initdb.d/
            - ./mysql/data:/var/lib/mysql
    
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "80:80"